config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]
  def index
    @docs = Doc.all
  end

  def show
    @docs = Doc.where(user_id: current_user)
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def find_doc
  end

  def doc_params
    params.require(:doc).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit

= link_to "Show Doc", docs_path

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    -unless @docs.blank?
      -@docs.each do |doc|
        %a{ href: (url_for [doc])}
        .doc
          %h2.title=  doc.title, doc
          %p.date= time_ago_in_words(doc.created_at)
          %p.content= truncate(doc.content, length:50)
    - else
      %h2 Create Doc!
      %p Start Creating Documents
      %button= link_to "Create Doc", new_doc_path

= link_to "New Doc", new_doc_path

app/views/docs/new.html.haml
= render 'form'

app/views/docs/show.html.haml
-@docs.each do |doc|
  %h2=doc.title
  %p=doc.content

= link_to "New Doc", new_doc_path

app/views/layouts/application.html.haml
!!!
%html
%head
  %title FileCabinet
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      .header_inner
        =link_to "FileCabinet", root_path, id:"logo"

        %nav
          - if user_signed_in?
            = link_to "Create Doc", new_doc_path
            = link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            = link_to "Log In", new_user_session_path
    %p.notice= notice
    %p.alert= alert

    = yield

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 File Cabinet
    %p Work RoadMap
    %button= link_to "Enter", new_user_registration_path

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organize
        %p Kickstarter

%bottom_cta
  .wrapper
    %h2 Go Ahead!
    %br
    %button= link_to "Join Now", new_user_registration_path